### ISSUE TITLE
Remaining steps for first working version (x86-64)

### ISSUE THREAD

**Issue by vincenthage** [proot-me/proot-rs#1]
Remaining steps for the bare minimum (single-tracee, no glue, no extensions, no ptrace-translation, no unix-socket translation, no qemu, -r/-R, -w and -b cli options only, no seccomp, and x86-64 with 64bits programs only):
#### Registers modification (`src/register`)
 - [x]  push regs
 - [x] set_sysarg_path
#### Path translations (`src/filesystem`)
 - [ ] symlinks translation
 - [ ] bindings initialisation
 - [ ] exe initialisation
#### Execve (`src/kernel/execve`)
 - [x] loader
 - [x] shebang
 - [x] enter
 - [ ] exit
#### Standard syscalls (`src/kernel/standard`)
Most of these are pretty much straightforward once the basic functions are covered (`translate_sysarg`).
Though there are a lot of them, and they all need to be unit/ci tested.
- [ ] chdir
- [ ] chmod_access_mknod_at
- [ ] dir_link_attr
- [ ] getcwd
- [ ] inotify_add_watch
- [ ] link_at
- [ ] link_rename
- [ ] mount
- [ ] open
- [ ] open_at
- [ ] pivot_root
- [ ] readlink_at
- [ ] rename_at
- [ ] standard_syscall
- [ ] stat_at
- [ ] sym_link
- [ ] sym_link_at
- [ ] uname
- [ ] unlink_mkdir_at
#### CLI (`src/cli`)
- [ ] exe
#### General
- [ ] tracees termination in case of tracer panicking.

**Comment by oxr463** [comment]
@jyn514, how do you feel about talking a swing at this?

**Comment by jyn514** [comment]
[`shebang`](https://github.com/proot-me/proot-rs/blob/master/src/kernel/execve/shebang.rs) looks like it already has a lot of code written, I could take a look at that tomorrow

**Comment by oxr463** [comment]
@KB5201314 do you think this is still relevant or can we close this?

**Comment by KB5201314** [comment]
> @KB5201314 do you think this is still relevant or can we close this?

Most of this has already been implemented, so I think we can close it now.
