### ISSUE TITLE
Unit test for working directory in guestfs

### ISSUE THREAD

**Issue by oxr463** [proot-me/proot-rs#26]
Do we have a unit test for this?

```
/// Working directory in guestfs, e.g., `/proc/self/cwd`, is always absolute
```

_Originally posted by @oxr463 in https://github.com/proot-me/proot-rs/pull/25#discussion_r645747165_

**Comment by KB5201314** [comment]
Unit tests for `cwd` field are included in [this PR](https://github.com/proot-me/proot-rs/pull/27/files#diff-a0093576833653774bfe7bf5ec11418e375decbfb58e9c9c7066933a67c66cd1R64):

https://github.com/proot-me/proot-rs/blob/9a00a8885e00eefb084f5930f7e9b4baad9ef418/src/kernel/standard/chdir.rs#L63-L70

More specifically, in the unit test function `test_chdir_fchdir_and_getcwd()`, a series of system calls are placed in tracee function (i.e., chdir() and fchdir()) to change the current working directory, and a hook function is placed in proot-rs to check if the `cwd` field is always a canonical path from start to finish.
