### ISSUE TITLE
Add support for Android platform and other architectures (e.g. arm, aarch64)

### ISSUE THREAD

**Issue by KB5201314** [proot-me/proot-rs#35]
The current implementation is written for Linux x86_64 and lacks support for android and arm/aarch64.

These issues need to be resolved:

- [x] Language support: rust has great support for the android platform
- [x] Third-party libraries: some libraries lack support for the android platform (e.g.[`sc`](https://github.com/japaric/syscall.rs)), some libraries behave differently on the arm/aarch64 architecture (e.g. missing `libc::user_regs_struct`)
- [x] Our code: need to write some extra code for arm/aarch64 (mainly the syscall and registers part).

**Comment by oxr463** [comment]
This is essential to our goal outlined in the project proposal:

> The desired result of the project is to be able to start an Alpine rootfs on a rootless Android
using proot-rs and to verify the goals presented above.

**Comment by oxr463** [comment]
Architectures:
- x86_64
- arm
- aarch64

**Comment by oxr463** [comment]
We currently have support for x86_64 and arm32v7 (See: https://www.notion.so/A-guide-to-quickly-test-alpine-and-nginx-on-Android-523a1c9b017942959153c3385ddd22a7). Support for aarch64 should be added this week.

**Comment by oxr463** [comment]
I tried testing in Termux on my Motorola G7, Android 10, and here is what I got:

```sh
./proot-rs --rootfs=./alpine --bind /dev:/dev --bind /proc:/proc
bash: ./proot-rs: Bad address
```

**Comment by KB5201314** [comment]
> I tried testing in Termux on my Motorola G7, Android 10, and here is what I got:
> 
> ```shell
> ./proot-rs --rootfs=./alpine --bind /dev:/dev --bind /proc:/proc
> bash: ./proot-rs: Bad address
> echo $?
> 126
> ```

Do you mean running proot-rs in the shell provided by the Temux app?

Also, what target are you using to build proot-rs, is it `arm-unknown-linux-musleabi`?

**Comment by oxr463** [comment]
> Do you mean running proot-rs in the shell provided by the Temux app?

Yes, it is Bash.

> Also, what target are you using to build proot-rs, is it `arm-unknown-linux-musleabi`?

Yes, per this, https://github.com/proot-me/proot-rs/pull/48#issuecomment-893508679

**Comment by oxr463** [comment]
```
termux-info
Application version:
0.117
Packages CPU architecture:
aarch64
Subscribed repositories:
# sources.list
deb https://packages.termux.org/apt/termux-main/ stable main
# game-repo (sources.list.d/game.list)
deb https://packages.termux.org/apt/termux-games games stable
# science-repo (sources.list.d/science.list)
deb https://packages.termux.org/apt/termux-science science stable
Updatable packages:
apt/stable 2.3.8 aarch64 [upgradable from: 2.3.7-4]
binutils/stable 2.37-1 aarch64 [upgradable from: 2.36.1]
golang/stable 2:1.17 aarch64 [upgradable from: 2:1.16.6]
Android version:
10
Kernel build information:
Linux localhost 4.9.206-perf+ #1 SMP PREEMPT Sun Sep 27 04:31:14 UTC 2020 aarch64 Android
Device manufacturer:
motorola
Device model:
moto g(7)
```

**Comment by oxr463** [comment]
@KB5201314 can we close this?

**Comment by KB5201314** [comment]
> @KB5201314 can we close this?

Yes, since we have been able to compile and also performed a simple manual test.
