### ISSUE TITLE
Continuous Integration

### ISSUE THREAD

**Issue by oxr463** [proot-me/proot-rs#5]
Tools

- [x] [Clippy](https://github.com/rust-lang/rust-clippy), (Docs: https://rust-lang.github.io/rust-clippy).
- [x] [rustfmt](https://github.com/rust-lang/rustfmt).
  - [x] Pre-commit hook
  - [x] Run in CI, (Travis Example: https://github.com/rust-lang/rustfmt#checking-style-on-a-ci-server).
- [x] [Cargo Tests](https://doc.rust-lang.org/cargo/guide/tests.html)
  - [Unit Tests](https://github.com/proot-me/proot-rs/issues/6)

Also, per conversation with @jyn514,
 
> run clippy before compiling, otherwise it won't output anything, it's an ongoing bug.

**Comment by jyn514** [comment]
Link to original clippy issue: https://github.com/rust-lang/rust-clippy/issues/2604

**Comment by oxr463** [comment]
- [ ] Update gcc dependency
```patch
[build-dependencies]
-gcc = { git = "https://github.com/vincenthage/gcc-rs", branch = "master" }
+gcc = { git = "https://github.com/alexcrichton/cc-rs", branch = "master" }
```
- [ ] Switch to nightly channel
```yaml
rust:
- nightly
```

**Comment by jyn514** [comment]
Just so you know, `cargo fmt --all && git diff --numstat | awk '{print $1 + $2}' | paste -sd+ | bc` shows 800 modified lines, which is a bit much to review by hand. Maybe only check formatting for modified files in each commit?

**Comment by oxr463** [comment]
But won't running `cargo fmt --all`, automatically fix the formatting?

How would I only check the formatting for modified files?

**Comment by jyn514** [comment]
Hmm... maybe something like this? `git status --porcelain | sed 's/^...//' | grep '*.rs' | xargs cargo fmt -v --`, see https://stackoverflow.com/questions/5237605/how-can-i-run-git-status-and-just-get-the-filenames#5238537

**Comment by jyn514** [comment]
Also the existing unit tests aren't passing, I'm taking a look at that now

**Comment by oxr463** [comment]
Closing per https://github.com/proot-me/proot-rs/pull/12
