### ISSUE TITLE
proot-rs --version doesn't show the version number

### ISSUE THREAD

**Issue by oxr463** [proot-me/proot-rs#58]
```
./proot-rs -V
proot-rs 
./proot-rs --version
proot-rs 
```

**Comment by KB5201314** [comment]
Seems that we forgot to add the version information in `cli.rs`: https://github.com/proot-me/proot-rs/blob/37dcb00022b61914aa62fd803c59b78dea82baab/proot-rs/src/cli.rs#L11-L33
