### ISSUE TITLE
Unit Testing

### ISSUE THREAD

**Issue by oxr463** [proot-me/proot-rs#6]
Resources:
  - [How to Write Tests](https://doc.rust-lang.org/book/ch11-01-writing-tests.html)

**Comment by KB5201314** [comment]
I will write a shell script that will automatically create a temporary rootfs directory before running `cargo test`

**Comment by KB5201314** [comment]
@oxr463 
I noticed a busybox based lite rootfs image:
https://github.com/docker-library/busybox/tree/dist-amd64/stable/glibc
This rootfs contains some basic directories, common commands, and a dynamic linkers and libc.so, which I think is suitable for testing proot-rs.

Another project called runc also uses the image here to create rootfs for integration tests.
https://github.com/opencontainers/runc/blob/0d49470392206f40eaab3b2190a57fe7bb3df458/tests/integration/get-images.sh#L56
