### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by oxr463** [proot-me/proot-rs#7]
There are two kinds of documentation required:
- [x] User manual, (See: https://github.com/proot-me/proot-rs#proot-rs)
- [x] Developer documentation, (See: https://github.com/proot-me/proot-rs/wiki)

Reference(s):
  - <s>[What is rustdoc?](https://doc.rust-lang.org/rustdoc/index.html)</s>
  - https://github.com/BurntSushi/ripgrep/blob/master/GUIDE.md

**Comment by KB5201314** [comment]
For the manual page, we can consider automatic generation with the help of a template in build.rs, like [this](https://github.com/BurntSushi/ripgrep/blob/64ac2ebe0f2fe1c8967e7ec550bc32466bf40a07/build.rs#L67)
